#define the main faction to show letters
def showLetters(myStr):
	#Arry of the 26 letters
	myLetters=[[	"   #   ",
		"  # #  ",
		" #   # ",
		"#######",
		"#     #",
		"#     #",
		"#     #"],
	[	"###### ",
		"#     #",
		"#     #",
		"###### ",
		"#     #",
		"#     #",
		"###### "],
	[	"  #####",
		" #     ",
		"#      ",
		"#      ",
		"#      ",
		" #     ",
		"  #####"],
	[	"#####  ",
		"#    # ",
		"#     #",
		"#     #",
		"#     #",
		"#    # ",
		"#####  "],
	[	"#######",
		"#      ",
		"#      ",
		"###### ",
		"#      ",
		"#      ",
		"#######"],
	[	"#######",
		"#      ",
		"#      ",
		"###### ",
		"#      ",
		"#      ",
		"#      "],
	[	"  #### ",
		" #     ",
		"#      ",
		"#   ###",
		"#     #",
		" #    #",
		"  #### "],
	[	"#     #",
		"#     #",
		"#     #",
		"#######",
		"#     #",
		"#     #",
		"#     #"],
	[	" ##### ",
		"   #   ",
		"   #   ",
		"   #   ",
		"   #   ",
		"   #   ",
		"#######"],
	[	"#######",
		"    #  ",
		"    #  ",
		"    #  ",
		"#   #  ",
		" #  #  ",
		"  ##   "],
	[	"#   ## ",
		"#  #   ",
		"# #    ",
		"##     ",
		"# #    ",
		"#  #   ",
		"#   ## "],
	[	"#      ",
		"#      ",
		"#      ",
		"#      ",
		"#      ",
		"#     #",
		"#######"],
	[	"#     #",
		"##   ##",
		"# # # #",
		"#  #  #",
		"#     #",
		"#     #",
		"#     #"],
	[	"#     #",
		"##    #",
		"# #   #",
		"#  #  #",
		"#   # #",
		"#    ##",
		"#     #"],
	[	"  ###  ",
		" #   # ",
		"#     #",
		"#     #",
		"#     #",
		" #   # ",
		"  ###  "],
	[	"###### ",
		"#     #",
		"#     #",
		"###### ",
		"#      ",
		"#      ",
		"#      "],
	[	"  ###  ",
		" #   # ",
		"#     #",
		"#     #",
		"#   # #",
		" #   # ",
		"  ### #"],
	[	"###### ",
		"#     #",
		"#     #",
		"###### ",
		"# #    ",
		"#  #   ",
		"#   ###"],
	[	" ##### ",
		"#     #",
		"#      ",
		" ##### ",
		"      #",
		"#     #",
		" ##### "],
	[	"#######",
		"   #   ",
		"   #   ",
		"   #   ",
		"   #   ",
		"   #   ",
		"   #   "],
	[	"#     #",
		"#     #",
		"#     #",
		"#     #",
		"#     #",
		"#     #",
		" ##### "],
	[	"#     #",
		"#     #",
		" #   # ",
		" #   # ",
		"  # #  ",
		"  # #  ",
		"   #   "],
	[	"#     #",
		"#     #",
		"#  #  #",
		"#  #  #",
		"#  #  #",
		" ## ## ",
		" #  #  "],
	[	"#     #",
		" #   # ",
		"  # #  ",
		"   #   ",
		"  # #  ",
		" #   # ",
		"#     #"],
	[	"#     #",
		" #   # ",
		"  # #  ",
		"   #   ",
		"   #   ",
		"   #   ",
		"   #   "],
	[	"#######",
		"     # ",
		"    #  ",
		"   #   ",
		"  #    ",
		" #     ",
		"#######"]]

	#Traverse the array to get every input letters
	myLetters_temp=myLetters[:]
	myNums = []
	for myLetters_temp in range(len(myStr)):
		myNums.append(ord(myStr[myLetters_temp])-65)

	#Make up the pattern
	for i in range(7):
		maxLenth = len(myNums)
		j=1
		for myNum in myNums:
			print myLetters[myNum][i]+"   ",
			if (j == maxLenth):
				print ""
				j=0
			j+=1

#make every 6 letters a new line
def startProgram(myStr):
	if (len(myStr))>6:
		print
		temp_myStr=myStr[0:6]
		showLetters(temp_myStr)
		myStr=myStr[6:]
		startProgram(myStr)
	else:
		print
		showLetters(myStr)
	
#Get the input letters and save as 'myStr'
myStr = raw_input("Please enter your name:").upper()
#Start the program
startProgram(myStr)
